# Generated by Django 2.0 on 2018-01-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
