# Generated by Django 2.0 on 2018-01-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserInfo',
        ),
    ]
